apiVersion: apps/v1
kind: Deployment
metadata:
  name: zsoxial-api-gateway
  namespace: zsoxial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
     labels:
       app: api_gateway
    spec:
      containers:
        - name: api-gateway-container
          image: akhi9550/zsoxial-api-gateway
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 212Mi
              cpu: ".2"
            requests:
              memory: 150Mi
              cpu: "0.1"



---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: zsoxial
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30003
  selector: 
    app: api_gateway