apiVersion: apps/v1
kind: Deployment
metadata:
  name: zsoxial-post-svc
  namespace: zsoxial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post_service
  template:
    metadata:
      labels: 
        app: post_service
    spec:
      containers:
      - image: akhi9550/zsoxial-post-service
        name: post-svc-container
        ports:
        - containerPort: 50052
        resources:
          limits:
            cpu: ".2"
            memory: "250Mi"
          requests:
            cpu: ".1"
            memory: "150Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  namespace: zsoxial
  name: zsoxial-post-service
spec:
  type: ClusterIP
  ports:
  - port: 50052
    targetPort: 50052
  selector:
    app: post_service